Introduce iOS simulator and Android emulator tests example
vividus-framework/vividus-sample-tests pull request #13
Opened 2022-06-03 08:46 UTC by ikalinin1

2022-06-03 14:54 UTC, valfirst requested changes

2022-06-03 14:54 UTC, valfirst commented on build.gradle
> +
```suggestion
```

2022-06-05 13:28 UTC, valfirst approved these changes

2022-06-06 07:51 UTC, uarlouski approved these changes

2022-06-06 08:21 UTC, merged